### ISSUE TITLE
weex-buildtool build init fails on macOS

### ISSUE THREAD

**Issue by mbokil** [Icemic/weex-buildtool#2]
After executing weex-buildtool build init I get an error. Error: Please exec weex init && npm install first. I have already executed weex init && npm install. I haven't found a way to get passed this point.

**Comment by Icemic** [comment]
Weex has changed its project directory structure, so buildtool cannot recognize it any more.

However, weex-buildtool is the prototype version of weex-pack, which is maintained by Weex Team now, and buildtool has stopped mantanance.

Please use https://github.com/weexteam/weex-pack now  : )

**Comment by mbokil** [comment]
Thanks I have switched to weex-pack and was able to build and run on ios.
